### PR TITLE
Possible fix for issue #383

### PR DESCRIPTION
**Pull request by gvanwaelvelde**
This could possibly fix issue #383 .
Just a suggestion...

### CODE REVIEW

**Comment by ericawright** [comment]
I tested it with a single file, size 0bytes, and I still received the "Uploading multiple files or a folder is currently not supported." message

**Comment by gvanwaelvelde** [comment]
Maybe we could use just one error message for both a folder and an empty file?
"Uploading an empty file or a folder is not allowed"
This is not ideal, and may even be confusing for some users, but when we can't differentiate between an empty file and a folder, we may have no choice.

**Comment by pdehaan** [comment]
Wow, this is pretty interesting... I'm seeing some different behavior on Chrome/Firefox with regards to folder sizes and how gracefully we handle empty folders vs folders with 1 file versus multiple files.

---

I have a file called "zerobytes.txt" which is just an empty file on my desktop.
If I drag that file into Firefox Send (using Firefox), it correctly says "Uploading an empty file is not allowed":

firefox_send

Chrome seems to agree:

firefox_send

firefox_send

---

Attempting to upload an empty directory into Firefox gives the same error message of "Uploading an empty file is not allowed". Not sure how to avoid that bit, since it still appears as a single file in a filelist with 0 bytes:

firefox_send

This is where Chrome starts to get a bit unexpected. Dropping an empty folder onto the drop zone tries uploading a directory, but takes me to the "Something went wrong!" page with an error. But note that Chrome reports an empty directory as having a size of 68 bytes.

firefox_send

Anyways. Not sure if dropping folders is a common-ish use case, or if that explains an error rate for "upload-stopped" with a `cd2` of "errored".

---

Chrome behavior seems equally baffling when you try dragging a folder with exactly 1 file versus a folder with multiple files.

The only consistency I see with dropping folders, is that Chrome (Release) and Firefox (Beta) both return a `FileList[0].type = ""` when dropping folders. But that feels way too brittle to try writing logic around.

**Comment by dannycoates** [comment]
I think other changes have superseded the need for this

**Pull request closed without merging**
