### PR TITLE
make the site mostly work when cookies (localStorage) are disabled

### PR DESCRIPTION
**Pull request by dannycoates**
In Firefox when cookies are disabled so is localStorage. The current version 1.1.0 is completely unusable when this is set and I've noticed a few related errors on sentry. 

This PR makes uploading and downloading work, but the file list (as expected) does not.

### CODE REVIEW

**Comment by pdehaan** [comment]
Q: Should we display some notification about "enhanced" file list functionality when a user has cookies disabled?

**Comment by dannycoates** [comment]
> Should we display some notification about "enhanced" file list functionality when a user has cookies disabled?

I think this would be a good follow-up issue for UX. There's other scenarios where localStorage isn't available as well. The one I'm thinking of is Firefox Focus. In that particular case maybe we want to assume the user doesn't expect to be able to see upload history at all, so notifying them would just be annoying?

**Comment by dannycoates** [comment]
Speaking of Focus, this PR makes uploading work for me on Focus for iOS, but download is still broken.

**Comment by ehuggett** [comment]
As the fallback storage eventually falls back to "map()" i presume this causes more issues as the file gets larger? (up to the point were it is unusable due to the memory consumption or the browser actually won't allow it)

From a quick search it appears to be possible to read a local file in memory in "chunks", which could be encrypted and uploaded before loading the next one. Files would presumably have to be uploaded slightly differently to accommodate this (or can you append data onto a HTTP post that is already in-progress? I assume not, so multiple POST's/etc)

The idea came from https://github.com/mozilla/send/issues/174

**Pull request merged**
