### PR TITLE
Delete button enhancement

### LINKED ISSUE #220: [Enhancement] Delete button should have a red background to help it stand out more
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a file and observe the "Delete" button.

[Expected result]:
- The button should keep the same aesthetic as the other action buttons from the site (Copy and Download buttons) and it would benefit from having a red background.

[Actual results]:
- The button has a clear background and black text.

[Notes]:
- Here is a screenshot with the issue:
image

### PR DESCRIPTION
**Pull request by perezbrandon**
delete button enhancement, gave it a red background to stand out more.

Fixes #220

### CODE REVIEW

**Comment by pdehaan** [comment]
Screenshot of new "Delete" button UI in https://github.com/mozilla/send/pull/483#issuecomment-321135105

**Comment by dannycoates** [comment]
@youwenliang thoughts?

**Comment by youwenliang** [comment]
From UX perspective the primary button on this screen should be the "copy link" button so we wouldn't want the red delete button to jump out and distract users.

Maybe we can do something more subtle like this:
image

And ideally, we should also put a confirmation dialog here just in case. (same as the one in the homepage)
image

**Comment by dannycoates** [comment]
Making the delete button red isn't what we want anymore.

**Pull request closed without merging**
