### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by varghesethomase**
Fixing #446  by replacing all `res.sendStatus(404);` with `res.status(404).render('notfound');`

### CODE REVIEW

**Comment by abhinadduri** [comment]
@varghesethomase We should only render the notfound page for HTML endpoints; some of the 404s are API endpoints and will not be expecting a notfound HTML page.

**Comment by varghesethomase** [comment]
@abhinadduri  Could you help me with identifying the APIs so that i can revert the necessary code?

**Comment by varghesethomase** [comment]
I guess the only non XHR request out there is for the /download url. I am reverting all the other code.  And have updated the PR.

**Comment by dannycoates** [comment]
Thank you @varghesethomase 😄

**Pull request merged**
