### PR TITLE
Update Vietnamese language

### PR DESCRIPTION
**Pull request by tdtgit**

### CODE REVIEW

**Comment by flodolo** [comment]
Hi, first of all thanks for your interest in localizing this feature.

While we welcome all contributions. as explained in the README, localization happens in a tool called Pontoon, not through pull requests.

A few side notes:
* Localization is not complete (I see a few strings in English)
* Extra comments will be stripped by localization tools

My suggestion would be to request the project on Pontoon, and agree with the existing team on the best process to use to review the translation.

@pierreneter @train255
You're both active on Pontoon for Vietnamese. Any thought on this?

**Comment by tdtgit** [comment]
Oh I see it. Can I close this PR and contribute by Pontoon tool?

**Comment by flodolo** [comment]
> Oh I see it. Can I close this PR and contribute by Pontoon tool?

Sure. I've enabled it on Pontoon, it will be available in about 20 minutes (next sync)
https://pontoon.mozilla.org/vi/

Note that you will be able to submit suggestions, a senior translator will review them (two of them are on this PR). If your translation gets stuck in review for a while, please ping me and we'll sort it out (in case reach out to my nickname on GH, plus @mozilla.com)

**Comment by pierreneter** [comment]
@flodolo thanks for your contribution.
Vi projects on Pontoon need your help.
If you have any questions you can also ask me.
And you can create translations for any project including vi projects on Pontoon tool, I will review it soonest for you (if they are translations of vi projects).
Once again. Thank you.

**Comment by tdtgit** [comment]
At this time Vietnamese language of Firefox Send on Pontoon is 100% suggested :)

**Pull request closed without merging**
