### PR TITLE
disable copying link when password not completed

### PR DESCRIPTION
**Pull request by ericawright**
select require password, the link and "copy" button get half opacity, and the button is disabled. When the checkbox is deselected or password is submitted the opacity is restored, and button is enabled.

result: 

screen shot 2017-10-23 at 9 55 59 am

Fixes: #606.
Fixes: #600.
Related: #587.

### CODE REVIEW

**Comment by ericawright** [comment]
@clouserw can you find me a re viewer for this please?

**Comment by wresuolc** [comment]
@fzzzy has volunteered.  thanks!

**Comment by fzzzy** [comment]
This looks good. I'd like to figure out how to build and test this locally so I can just verify it does what I think it does.

**Comment by fzzzy** [comment]
This works well, but I did notice one tiny bug. I think it is mostly a nit.

To reproduce, click the copy button, then click the password button while the green checkmark is still visible in the copy button. The copy button will be rendered as faded out, but it will not be disabled and the user will be able to click it to copy the url again.

I think this is because after the `await delay(2000)`, `copyBtn.disabled = false;` is being executed even if the password checkbox is now checked. This is a weird corner case and it is probably fine if it doesn't get fixed.

**Comment by ericawright** [comment]
nit has been fixed, that @fzzzy

**Pull request merged**
