### PR TITLE
Cleanup Android project (Minor refactorings, etc.)

### PR DESCRIPTION
**Pull request by christxph**
Cleaned up a few files related to the Android project to follow common Android/Kotlin conventions.

### CODE REVIEW

**Comment by fzzzy** [comment]
Thank you very much! I'll take a look next week.

**Comment by christxph** [comment]
Thanks for the review, I will look into this later today and update the PR.

**Comment by christxph** [comment]
Hi,
unfortunately I am currently experiencing the same behavior (sign-up button doesn't respond and choosing a file does not cause it to be added) on _both_, the latest `master` and this branch (`android-cleanup`). 
Can you build the latest `master` and use the two mentioned features as expected?

Also rebased on the latest `master`.

**Comment by fzzzy** [comment]
@christxph Yes, I see master being broken also. @dannycoates Did anything happen on master recently that might have broken android?

**Comment by christxph** [comment]
Alright, I will add an instrumentation test to this branch that verifies that the sign up button does anything so that it's easier to test this issue.

**Comment by fzzzy** [comment]
I'm going to take another swing at getting this branch running tomorrow.

**Comment by fzzzy** [comment]
Master is fixed now, and this branch looks good. Thank you very much!

**Pull request merged**
