### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by tabasano**

### CODE REVIEW

**Comment by flodolo** [comment]
Hi, ideally we would like all localization contributions to go through Pontoon, for proper history and attribution
https://pontoon.mozilla.org/ja/test-pilot-firefox-send/

Having said that, if @kyoshino doesn't have any objection, I think we can merge this.

**Comment by kyoshino** [comment]
Ah my bad, I just fixed in on [Pontoon](https://pontoon.mozilla.org/ja/test-pilot-firefox-send/send.ftl/?status=translated&string=168999) (encrypt -> decrypt). Thank you tabasano san!

**Comment by flodolo** [comment]
https://github.com/mozilla/send/commit/73e39ad4531498f944239652df31491dc56bceba

**Comment by tabasano** [comment]
Hi, I'll try the suggested way the next time I find typo, if any.
thanks.

**Pull request closed without merging**
