### PR TITLE
Hide password while Typing and after Entering: Fixes #670 

### LINKED ISSUE #670: Password should be hidden while typing
After uploading a file, Password while typing is not hidden.

### PR DESCRIPTION
**Pull request by shikhar-scs**
As suggested by @dannycoates #673 all the requested changes have been made. Here's a preview
(its a gif file, please be patient while it loads)
Also Fixes #670 

ezgif com-video-to-gif

Please review

### CODE REVIEW

**Comment by shikhar-scs** [comment]
the commit 3610670f992d5b93e0909fb474cc1ea7dbd24c13 actually references #679. I'll stash that here.

**Comment by shikhar-scs** [comment]
@dannycoates Do you mind giving a review ? Its been 10 days

**Comment by shikhar-scs** [comment]
With this latest commit, the set password is now toggleable, i.e., normally it is starred and on hover, the original password is displayed.
Here's a preview for the same (its a gif file, please be patient while it loads)

sendpassword

@dannycoates Please review

**Comment by dannycoates** [comment]
The code looks ok. @sevaan, what do you think about the design and hover to reveal? I think we should use ● (U+25CF) instead of * though.

**Comment by shikhar-scs** [comment]
> I think we should use ● (U+25CF) instead of * though.

If that is the case, I'll do that right away. Is it fine otherwise ?

**Comment by sevaan** [comment]
> The code looks ok. @sevaan, what do you think about the design and hover to reveal? I think we should use ● (U+25CF) instead of * though.

Looks great! Good idea. And let's use U+25CF, it'll be much cleaner. Thanks!

**Comment by shikhar-scs** [comment]
I have made the required changes. Here's a preview
ezgif com-video-to-bvkufdugif

**Comment by shikhar-scs** [comment]
I have made the required changes, here's a preview
latest

**Comment by dannycoates** [comment]
Thanks @shikhar-scs 😄

**Comment by shikhar-scs** [comment]
Welcome @dannycoates :smile:

**Pull request merged**
