### PR TITLE
Added Polish pl_PL localization

### PR DESCRIPTION
**Pull request by craftystudio**
Polish translation of Firefox Send.

### CODE REVIEW

**Comment by dannycoates** [comment]
Thank you @craftystudio. Pontoon (https://pontoon.mozilla.org/projects/test-pilot-firefox-send/) is our localization interface. Please add any new translations there where they will be reviewed and automatically merged into the project.

**Comment by flodolo** [comment]
Hi, thanks for your interest in contributing.

I'm ccing one of our localizers on Pontoon (@piotrdrag). The project is currently not enabled in Pontoon, but it can be requested, and we can try to salvage content from the work you've done.

I'm sure Piotr will appreciate all the help you can give him, we're really short on localizers for Polish.

**Comment by piotrdrag** [comment]
I’ve requested enabling the project in Pontoon.

**Comment by piotrdrag** [comment]
Hi @craftystudio! Could you create an account in Pontoon (https://pontoon.mozilla.org/pl/) and copy your translations to the Firefox Send project there?

**Comment by craftystudio** [comment]
Sure, I will do it.

**Pull request closed without merging**
