### PR TITLE
Remove the leak of the password into the console

### PR DESCRIPTION
**Pull request by laurentj**

### CODE REVIEW

**Comment by julienw** [comment]
ping @dannycoates ;)

**Comment by sylvestre** [comment]
This has been mentioned in the french press:
https://www.nextinpact.com/brief/firefox-send---protection-par-mot-de-passe--qui-sera-logue-dans-la-console-en-cas-de-telechargement-1285.htm

**Comment by laurentj** [comment]
Yes, I proposed the patch after reading the Nextinpact article :-)

**Comment by sylvestre** [comment]
I figured ;) It is to make sure reviewers are aware when they see your PR!

**Comment by dannycoates** [comment]
Thank you @laurentj 😄

**Comment by dannycoates** [comment]
this is now live on https://send.firefox.com

**Pull request merged**
